# Generated by Django 2.1.5 on 2020-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_and_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_no', models.CharField(blank=True, max_length=10, null=True)),
                ('uni_major', models.CharField(blank=True, choices=[('CE', 'CE'), ('EE', 'EE'), ('OTHER_MAJ', 'OTHER_MAJ')], max_length=20, null=True)),
                ('uni_position', models.CharField(blank=True, choices=[('PROF', 'PROF'), ('researcher', 'researcher'), ('OTHER_POS', 'OTHER_POS')], max_length=20, null=True)),
                ('uni_name', models.CharField(blank=True, choices=[('SUT', 'SUT'), ('UOT', 'UOT'), ('OTHER_UNI', 'OTHER_UNI')], max_length=40, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_graduated', models.BooleanField(default=False)),
                ('id_professor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
